# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWtabs.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 636)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.vistas = QtGui.QTabWidget(self.centralwidget)
        self.vistas.setEnabled(True)
        self.vistas.setGeometry(QtCore.QRect(10, 10, 781, 601))
        self.vistas.setDocumentMode(False)
        self.vistas.setTabsClosable(False)
        self.vistas.setObjectName(_fromUtf8("vistas"))
        self.widget = QtGui.QWidget()
        self.widget.setEnabled(True)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.boton_login = QtGui.QPushButton(self.widget)
        self.boton_login.setGeometry(QtCore.QRect(338, 440, 121, 31))
        self.boton_login.setObjectName(_fromUtf8("boton_login"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(238, 330, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(238, 380, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(258, 20, 261, 261))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setAutoFillBackground(False)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("Imagenes/businessman-3.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.username = QtGui.QLineEdit(self.widget)
        self.username.setGeometry(QtCore.QRect(348, 320, 161, 29))
        self.username.setObjectName(_fromUtf8("username"))
        self.password = QtGui.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(350, 370, 161, 29))
        self.password.setObjectName(_fromUtf8("password"))
        self.vistas.addTab(self.widget, _fromUtf8(""))
        self.tab_persona = QtGui.QWidget()
        self.tab_persona.setEnabled(False)
        self.tab_persona.setObjectName(_fromUtf8("tab_persona"))
        self.numero_dentidad = QtGui.QLineEdit(self.tab_persona)
        self.numero_dentidad.setGeometry(QtCore.QRect(320, 150, 171, 29))
        self.numero_dentidad.setObjectName(_fromUtf8("numero_dentidad"))
        self.label_10 = QtGui.QLabel(self.tab_persona)
        self.label_10.setGeometry(QtCore.QRect(120, 100, 161, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.fecha_nacimiento = QtGui.QDateEdit(self.tab_persona)
        self.fecha_nacimiento.setGeometry(QtCore.QRect(320, 200, 151, 29))
        self.fecha_nacimiento.setObjectName(_fromUtf8("fecha_nacimiento"))
        self.primer_apellido = QtGui.QLineEdit(self.tab_persona)
        self.primer_apellido.setGeometry(QtCore.QRect(320, 300, 161, 29))
        self.primer_apellido.setObjectName(_fromUtf8("primer_apellido"))
        self.label_4 = QtGui.QLabel(self.tab_persona)
        self.label_4.setGeometry(QtCore.QRect(120, 150, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.combo_box_desempeno = QtGui.QComboBox(self.tab_persona)
        self.combo_box_desempeno.setGeometry(QtCore.QRect(320, 100, 251, 27))
        self.combo_box_desempeno.setEditable(False)
        self.combo_box_desempeno.setModelColumn(0)
        self.combo_box_desempeno.setObjectName(_fromUtf8("combo_box_desempeno"))
        self.combo_box_desempeno.addItem(_fromUtf8(""))
        self.combo_box_desempeno.addItem(_fromUtf8(""))
        self.combo_box_desempeno.addItem(_fromUtf8(""))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.tab_persona)
        self.doubleSpinBox.setGeometry(QtCore.QRect(320, 350, 161, 29))
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.label_5 = QtGui.QLabel(self.tab_persona)
        self.label_5.setGeometry(QtCore.QRect(120, 200, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_11 = QtGui.QLabel(self.tab_persona)
        self.label_11.setGeometry(QtCore.QRect(120, 350, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_6 = QtGui.QLabel(self.tab_persona)
        self.label_6.setGeometry(QtCore.QRect(120, 300, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_8 = QtGui.QLabel(self.tab_persona)
        self.label_8.setGeometry(QtCore.QRect(120, 300, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_7 = QtGui.QLabel(self.tab_persona)
        self.label_7.setGeometry(QtCore.QRect(120, 250, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.primer_nombre = QtGui.QLineEdit(self.tab_persona)
        self.primer_nombre.setGeometry(QtCore.QRect(320, 250, 161, 29))
        self.primer_nombre.setObjectName(_fromUtf8("primer_nombre"))
        self.boton_confirmar = QtGui.QPushButton(self.tab_persona)
        self.boton_confirmar.setGeometry(QtCore.QRect(580, 440, 97, 29))
        self.boton_confirmar.setObjectName(_fromUtf8("boton_confirmar"))
        self.vistas.addTab(self.tab_persona, _fromUtf8(""))
        self.tab_club = QtGui.QWidget()
        self.tab_club.setEnabled(False)
        self.tab_club.setObjectName(_fromUtf8("tab_club"))
        self.label_9 = QtGui.QLabel(self.tab_club)
        self.label_9.setGeometry(QtCore.QRect(260, 10, 241, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.botonEliminarEquipo = QtGui.QPushButton(self.tab_club)
        self.botonEliminarEquipo.setGeometry(QtCore.QRect(320, 310, 91, 29))
        self.botonEliminarEquipo.setObjectName(_fromUtf8("botonEliminarEquipo"))
        self.label_12 = QtGui.QLabel(self.tab_club)
        self.label_12.setGeometry(QtCore.QRect(480, 110, 151, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.botonAceptar = QtGui.QPushButton(self.tab_club)
        self.botonAceptar.setGeometry(QtCore.QRect(580, 510, 97, 29))
        self.botonAceptar.setObjectName(_fromUtf8("botonAceptar"))
        self.botonAgregarEquipo = QtGui.QPushButton(self.tab_club)
        self.botonAgregarEquipo.setGeometry(QtCore.QRect(320, 260, 91, 29))
        self.botonAgregarEquipo.setObjectName(_fromUtf8("botonAgregarEquipo"))
        self.label_13 = QtGui.QLabel(self.tab_club)
        self.label_13.setGeometry(QtCore.QRect(100, 110, 141, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.botonActualizarEqui = QtGui.QPushButton(self.tab_club)
        self.botonActualizarEqui.setGeometry(QtCore.QRect(290, 510, 141, 29))
        self.botonActualizarEqui.setObjectName(_fromUtf8("botonActualizarEqui"))
        self.listaEquiposDisp = QtGui.QListWidget(self.tab_club)
        self.listaEquiposDisp.setGeometry(QtCore.QRect(40, 130, 271, 361))
        self.listaEquiposDisp.setObjectName(_fromUtf8("listaEquiposDisp"))
        self.listaEquiposSel = QtGui.QListWidget(self.tab_club)
        self.listaEquiposSel.setGeometry(QtCore.QRect(420, 130, 271, 361))
        self.listaEquiposSel.setObjectName(_fromUtf8("listaEquiposSel"))
        self.vistas.addTab(self.tab_club, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.texIntTemporada = QtGui.QLineEdit(self.tab_2)
        self.texIntTemporada.setGeometry(QtCore.QRect(220, 40, 161, 29))
        self.texIntTemporada.setObjectName(_fromUtf8("texIntTemporada"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(40, 40, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.equiposPart = QtGui.QListWidget(self.tab_2)
        self.equiposPart.setGeometry(QtCore.QRect(40, 180, 271, 271))
        self.equiposPart.setObjectName(_fromUtf8("equiposPart"))
        self.equiposDisp = QtGui.QListWidget(self.tab_2)
        self.equiposDisp.setGeometry(QtCore.QRect(440, 180, 281, 271))
        self.equiposDisp.setObjectName(_fromUtf8("equiposDisp"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(40, 130, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(470, 20, 241, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(430, 40, 291, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.botonCrearTemp = QtGui.QPushButton(self.tab_2)
        self.botonCrearTemp.setGeometry(QtCore.QRect(70, 490, 211, 41))
        self.botonCrearTemp.setObjectName(_fromUtf8("botonCrearTemp"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(440, 130, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.botonAgregarEquipo_2 = QtGui.QPushButton(self.tab_2)
        self.botonAgregarEquipo_2.setGeometry(QtCore.QRect(480, 490, 211, 41))
        self.botonAgregarEquipo_2.setObjectName(_fromUtf8("botonAgregarEquipo_2"))
        self.cargarEquiposTemp = QtGui.QPushButton(self.tab_2)
        self.cargarEquiposTemp.setGeometry(QtCore.QRect(530, 90, 97, 29))
        self.cargarEquiposTemp.setObjectName(_fromUtf8("cargarEquiposTemp"))
        self.vistas.addTab(self.tab_2, _fromUtf8(""))
        self.tabEquipo = QtGui.QWidget()
        self.tabEquipo.setEnabled(False)
        self.tabEquipo.setObjectName(_fromUtf8("tabEquipo"))
        self.recuperarJugadores = QtGui.QPushButton(self.tabEquipo)
        self.recuperarJugadores.setGeometry(QtCore.QRect(520, 450, 181, 29))
        self.recuperarJugadores.setObjectName(_fromUtf8("recuperarJugadores"))
        self.label_20 = QtGui.QLabel(self.tabEquipo)
        self.label_20.setGeometry(QtCore.QRect(50, 210, 201, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tabEquipo)
        self.label_21.setGeometry(QtCore.QRect(120, 100, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lista_jugadores_disp = QtGui.QListWidget(self.tabEquipo)
        self.lista_jugadores_disp.setGeometry(QtCore.QRect(470, 240, 256, 192))
        self.lista_jugadores_disp.setObjectName(_fromUtf8("lista_jugadores_disp"))
        self.boton_agregar__jug_equipo = QtGui.QPushButton(self.tabEquipo)
        self.boton_agregar__jug_equipo.setGeometry(QtCore.QRect(350, 320, 85, 27))
        self.boton_agregar__jug_equipo.setObjectName(_fromUtf8("boton_agregar__jug_equipo"))
        self.label_22 = QtGui.QLabel(self.tabEquipo)
        self.label_22.setGeometry(QtCore.QRect(480, 210, 201, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.texto_nom_equipo = QtGui.QLineEdit(self.tabEquipo)
        self.texto_nom_equipo.setGeometry(QtCore.QRect(310, 110, 371, 29))
        self.texto_nom_equipo.setObjectName(_fromUtf8("texto_nom_equipo"))
        self.boton_equipo_aceptar = QtGui.QPushButton(self.tabEquipo)
        self.boton_equipo_aceptar.setGeometry(QtCore.QRect(660, 510, 97, 29))
        self.boton_equipo_aceptar.setObjectName(_fromUtf8("boton_equipo_aceptar"))
        self.lista_jugadores_ag = QtGui.QListWidget(self.tabEquipo)
        self.lista_jugadores_ag.setGeometry(QtCore.QRect(30, 240, 256, 192))
        self.lista_jugadores_ag.setObjectName(_fromUtf8("lista_jugadores_ag"))
        self.vistas.addTab(self.tabEquipo, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setEnabled(False)
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.comboBox_7 = QtGui.QComboBox(self.tab_8)
        self.comboBox_7.setGeometry(QtCore.QRect(210, 30, 181, 31))
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.listWidget = QtGui.QListWidget(self.tab_8)
        self.listWidget.setGeometry(QtCore.QRect(40, 170, 291, 321))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.label_58 = QtGui.QLabel(self.tab_8)
        self.label_58.setGeometry(QtCore.QRect(20, 40, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_59 = QtGui.QLabel(self.tab_8)
        self.label_59.setGeometry(QtCore.QRect(40, 140, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_8)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 500, 121, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_60 = QtGui.QLabel(self.tab_8)
        self.label_60.setGeometry(QtCore.QRect(420, 140, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.listWidget_2 = QtGui.QListWidget(self.tab_8)
        self.listWidget_2.setGeometry(QtCore.QRect(420, 170, 291, 321))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_8)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 500, 151, 31))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.cargar_cbEquipos = QtGui.QPushButton(self.tab_8)
        self.cargar_cbEquipos.setGeometry(QtCore.QRect(520, 30, 97, 29))
        self.cargar_cbEquipos.setObjectName(_fromUtf8("cargar_cbEquipos"))
        self.vistas.addTab(self.tab_8, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.comboBox = QtGui.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(40, 80, 161, 31))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox_2 = QtGui.QComboBox(self.tab_3)
        self.comboBox_2.setGeometry(QtCore.QRect(300, 80, 161, 31))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_3 = QtGui.QComboBox(self.tab_3)
        self.comboBox_3.setGeometry(QtCore.QRect(550, 80, 161, 31))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(70, 50, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(350, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(560, 50, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.tableWidget = QtGui.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(20, 180, 261, 81))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(510, 180, 181, 91))
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.label_49 = QtGui.QLabel(self.tab_3)
        self.label_49.setGeometry(QtCore.QRect(290, 130, 171, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_50 = QtGui.QLabel(self.tab_3)
        self.label_50.setGeometry(QtCore.QRect(130, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.label_51 = QtGui.QLabel(self.tab_3)
        self.label_51.setGeometry(QtCore.QRect(550, 150, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.label_52 = QtGui.QLabel(self.tab_3)
        self.label_52.setGeometry(QtCore.QRect(120, 280, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_53 = QtGui.QLabel(self.tab_3)
        self.label_53.setGeometry(QtCore.QRect(500, 280, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.tableWidget_3 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(30, 310, 231, 171))
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.tableWidget_4 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(460, 310, 231, 171))
        self.tableWidget_4.setObjectName(_fromUtf8("tableWidget_4"))
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.label_54 = QtGui.QLabel(self.tab_3)
        self.label_54.setGeometry(QtCore.QRect(310, 380, 21, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_55 = QtGui.QLabel(self.tab_3)
        self.label_55.setGeometry(QtCore.QRect(350, 380, 21, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_56 = QtGui.QLabel(self.tab_3)
        self.label_56.setGeometry(QtCore.QRect(380, 380, 21, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.radioButton = QtGui.QRadioButton(self.tab_3)
        self.radioButton.setGeometry(QtCore.QRect(50, 510, 100, 22))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_2.setGeometry(QtCore.QRect(170, 510, 100, 22))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.tab_3)
        self.radioButton_3.setGeometry(QtCore.QRect(320, 510, 100, 22))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(460, 500, 231, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(560, 10, 121, 20))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.labelMoney = QtGui.QLabel(self.tab_3)
        self.labelMoney.setGeometry(QtCore.QRect(690, 10, 64, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.labelMoney.setPalette(palette)
        self.labelMoney.setObjectName(_fromUtf8("labelMoney"))
        self.botonTemporadas = QtGui.QPushButton(self.tab_3)
        self.botonTemporadas.setGeometry(QtCore.QRect(330, 190, 97, 27))
        self.botonTemporadas.setObjectName(_fromUtf8("botonTemporadas"))
        self.botonPartidos = QtGui.QPushButton(self.tab_3)
        self.botonPartidos.setGeometry(QtCore.QRect(330, 240, 97, 27))
        self.botonPartidos.setObjectName(_fromUtf8("botonPartidos"))
        self.vistas.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.list_con_datos = QtGui.QListWidget(self.tab)
        self.list_con_datos.setGeometry(QtCore.QRect(95, 120, 591, 391))
        self.list_con_datos.setObjectName(_fromUtf8("list_con_datos"))
        self.label_26 = QtGui.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(190, 20, 211, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.combo_consulta = QtGui.QComboBox(self.tab)
        self.combo_consulta.setGeometry(QtCore.QRect(190, 70, 391, 25))
        self.combo_consulta.setObjectName(_fromUtf8("combo_consulta"))
        self.combo_consulta.addItem(_fromUtf8(""))
        self.combo_consulta.addItem(_fromUtf8(""))
        self.combo_consulta.addItem(_fromUtf8(""))
        self.combo_consulta.addItem(_fromUtf8(""))
        self.combo_consulta.addItem(_fromUtf8(""))
        self.combo_consulta.addItem(_fromUtf8(""))
        self.combo_consulta.addItem(_fromUtf8(""))
        self.vistas.addTab(self.tab, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.boton_salir = QtGui.QPushButton(self.tab_7)
        self.boton_salir.setGeometry(QtCore.QRect(230, 210, 331, 291))
        self.boton_salir.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Imagenes/logout (1).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_salir.setIcon(icon)
        self.boton_salir.setIconSize(QtCore.QSize(230, 230))
        self.boton_salir.setFlat(True)
        self.boton_salir.setObjectName(_fromUtf8("boton_salir"))
        self.label_57 = QtGui.QLabel(self.tab_7)
        self.label_57.setGeometry(QtCore.QRect(280, 60, 231, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.vistas.addTab(self.tab_7, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.vistas.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.boton_login.setText(_translate("MainWindow", "Log In", None))
        self.label_2.setText(_translate("MainWindow", "Usuario", None))
        self.label_3.setText(_translate("MainWindow", "Password", None))
        self.vistas.setTabText(self.vistas.indexOf(self.widget), _translate("MainWindow", "Administrador", None))
        self.label_10.setText(_translate("MainWindow", "Se desempenara como ::", None))
        self.fecha_nacimiento.setDisplayFormat(_translate("MainWindow", "dd/mm/yyyy", None))
        self.label_4.setText(_translate("MainWindow", "Numero de identidad ", None))
        self.combo_box_desempeno.setItemText(0, _translate("MainWindow", "Arbitro", None))
        self.combo_box_desempeno.setItemText(1, _translate("MainWindow", "Jugador", None))
        self.combo_box_desempeno.setItemText(2, _translate("MainWindow", "Entrenador", None))
        self.label_5.setText(_translate("MainWindow", "Fecha de nacimiento ", None))
        self.label_11.setText(_translate("MainWindow", "Peso", None))
        self.label_8.setText(_translate("MainWindow", "Primer Apellido", None))
        self.label_7.setText(_translate("MainWindow", "Primer Nombre", None))
        self.boton_confirmar.setText(_translate("MainWindow", "Aceptar", None))
        self.vistas.setTabText(self.vistas.indexOf(self.tab_persona), _translate("MainWindow", "Crear persona", None))
        self.label_9.setText(_translate("MainWindow", "Nuevo Club Deportivo", None))
        self.botonEliminarEquipo.setText(_translate("MainWindow", "<-Eliminar", None))
        self.label_12.setText(_translate("MainWindow", "Equipos Seleccionados", None))
        self.botonAceptar.setText(_translate("MainWindow", "Aceptar", None))
        self.botonAgregarEquipo.setText(_translate("MainWindow", "Agegar ->", None))
        self.label_13.setText(_translate("MainWindow", "Equipos Disponibles", None))
        self.botonActualizarEqui.setText(_translate("MainWindow", "Actualizar Equipos", None))
        self.vistas.setTabText(self.vistas.indexOf(self.tab_club), _translate("MainWindow", "Crear Club", None))
        self.label_15.setText(_translate("MainWindow", "Temporada", None))
        self.label_16.setText(_translate("MainWindow", "Equipos participantes", None))
        self.label_17.setText(_translate("MainWindow", "Nota: La cantidad maxima", None))
        self.label_18.setText(_translate("MainWindow", "es de 15 equipos participantes", None))
        self.botonCrearTemp.setText(_translate("MainWindow", "Crear temporada", None))
        self.label_19.setText(_translate("MainWindow", "Equipos disponibles", None))
        self.botonAgregarEquipo_2.setText(_translate("MainWindow", "Agregar equipo", None))
        self.cargarEquiposTemp.setText(_translate("MainWindow", "Cargar", None))
        self.vistas.setTabText(self.vistas.indexOf(self.tab_2), _translate("MainWindow", "Crear Temporada", None))
        self.recuperarJugadores.setText(_translate("MainWindow", "Recuperar Jugadores", None))
        self.label_20.setText(_translate("MainWindow", "Jugadores Agregados", None))
        self.label_21.setText(_translate("MainWindow", "Nombre del Equipo:", None))
        self.boton_agregar__jug_equipo.setText(_translate("MainWindow", "<- Agregar", None))
        self.label_22.setText(_translate("MainWindow", "Jugadores Disponibles", None))
        self.boton_equipo_aceptar.setText(_translate("MainWindow", "Aceptar", None))
        self.vistas.setTabText(self.vistas.indexOf(self.tabEquipo), _translate("MainWindow", "Equipos", None))
        self.label_58.setText(_translate("MainWindow", "Seleccionar equipo", None))
        self.label_59.setText(_translate("MainWindow", "Plantilla", None))
        self.pushButton_2.setText(_translate("MainWindow", "Eliminar", None))
        self.label_60.setText(_translate("MainWindow", "Agentes libres", None))
        self.pushButton_3.setText(_translate("MainWindow", "Agregar", None))
        self.cargar_cbEquipos.setText(_translate("MainWindow", "Cargar", None))
        self.vistas.setTabText(self.vistas.indexOf(self.tab_8), _translate("MainWindow", "Modificar equipo", None))
        self.label_14.setText(_translate("MainWindow", "Temporada", None))
        self.label_23.setText(_translate("MainWindow", "Jornada", None))
        self.label_24.setText(_translate("MainWindow", "Enfrentamiento", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Arbitro principal", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Arbitro auxiliar 1", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Arbitro auxiliar 2", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Arbitro de reserva", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre", None))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Local", None))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Visitante", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre", None))
        self.label_49.setText(_translate("MainWindow", "Informacion del partido", None))
        self.label_50.setText(_translate("MainWindow", "Arbitros", None))
        self.label_51.setText(_translate("MainWindow", "Entrenadores", None))
        self.label_52.setText(_translate("MainWindow", "Local - ", None))
        self.label_53.setText(_translate("MainWindow", "Visitante -", None))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_3.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_3.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tableWidget_3.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9", None))
        item = self.tableWidget_3.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget_3.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Biorritmo", None))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_4.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_4.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_4.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tableWidget_4.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9", None))
        item = self.tableWidget_4.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget_4.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11", None))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre", None))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Biorritmo", None))
        self.label_54.setText(_translate("MainWindow", "0", None))
        self.label_55.setText(_translate("MainWindow", "-", None))
        self.label_56.setText(_translate("MainWindow", "0", None))
        self.radioButton.setText(_translate("MainWindow", "Local", None))
        self.radioButton_2.setText(_translate("MainWindow", "Empate", None))
        self.radioButton_3.setText(_translate("MainWindow", "Visita", None))
        self.pushButton.setText(_translate("MainWindow", "JUGAR", None))
        self.label_25.setText(_translate("MainWindow", "Balance Actual: $", None))
        self.labelMoney.setText(_translate("MainWindow", "100.00", None))
        self.botonTemporadas.setText(_translate("MainWindow", "Cargar T", None))
        self.botonPartidos.setText(_translate("MainWindow", "Cargar P", None))
        self.vistas.setTabText(self.vistas.indexOf(self.tab_3), _translate("MainWindow", "Jugar", None))
        self.label_26.setText(_translate("MainWindow", "Consultar datos de:", None))
        self.combo_consulta.setItemText(0, _translate("MainWindow", "Personas", None))
        self.combo_consulta.setItemText(1, _translate("MainWindow", "Jugadores", None))
        self.combo_consulta.setItemText(2, _translate("MainWindow", "Entrenadores", None))
        self.combo_consulta.setItemText(3, _translate("MainWindow", "Arbitros", None))
        self.combo_consulta.setItemText(4, _translate("MainWindow", "Equipos", None))
        self.combo_consulta.setItemText(5, _translate("MainWindow", "Clubes", None))
        self.combo_consulta.setItemText(6, _translate("MainWindow", "Partidos", None))
        self.vistas.setTabText(self.vistas.indexOf(self.tab), _translate("MainWindow", "Consultas", None))
        self.label_57.setText(_translate("MainWindow", "SALIR", None))
        self.vistas.setTabText(self.vistas.indexOf(self.tab_7), _translate("MainWindow", "Salir", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

